config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "customers#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get  	 "/logins", 					              to: "logins#index"
  get  	 "/logins/:customer_id", 			      to: "logins#show"
  post 	 "/logins/create", 		              to: "logins#create"
  delete "/logins/destroy/:login_id", 	    to: "logins#destroy",     as: :logins_destroy
  delete "/customers/destroy/:customer_id", to: "customers#destroy",  as: :customers_destroy
  get  	 "/transactions/:account_id",       to: "transactions#index", as: :transactions
  get 	 "/accounts/:login_id",             to: "accounts#index",     as: :accounts
  get 	 "/customers", 				              to: "customers#index"
  put    "/logins/refresh/:login_id",       to: "logins#refresh",     as: :logins_refresh
  put    "/logins/reconnect/:login_id",     to: "logins#reconnect",   as: :logins_reconnect

  # resources :logins, only: %i(create destroy show index)

  # resources :customers, only: :index do
  # 	resources :logins, only: :index do
  # 		resources :accounts, only: :index do
  #       resources :transactions, only: :index
  #     end
  # 	end
 	# end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def index
    @accounts = Spectre.get_accounts(params[:login_id])["data"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :authenticate_user!

	def index
		@customers = Spectre.get_customers["data"]
	end

	def destroy
		Spectre.delete("/customers/#{params[:customer_id]}")
		redirect_to customers_path
	end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :authenticate_user!, :create_customer

  def index
    return redirect_to customers_path unless params[:customer_id]

    @logins = Spectre.get_logins(params[:customer_id])["data"]
  end

  def destroy
    Spectre.delete("/logins/#{params[:login_id]}")
    redirect_to logins_path(customer_id: params[:customer_id])
  end

  def refresh
    Spectre.put("/logins/#{params[:login_id]}/refresh")
    redirect_to logins_path(customer_id: params[:customer_id])
  end

  def reconnect
    Spectre.put("/logins/#{params[:login_id]}/reconnect")
    redirect_to logins_path(customer_id: params[:customer_id])
  end

  def create
    url = Spectre.create_connection(current_user.spectre_id)["data"]["connect_url"]
    redirect_to url
  end

  def create_customer
    return if current_user.spectre_id.present?
    customer_id = Spectre.create_customer(current_user.email)["data"]["id"]
    current_user.update!(spectre_id: customer_id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @transactions = Spectre.get_transactions(params[:account_id])["data"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/accounts/index.html.erb
<table id="customers">
  <tr>
    <th>Account ID</th>
    <th>Account Name</th>
    <th>Nature</th>
    <th>Balance</th>
    <th>Currency Code</th>
    <th>Transactions</th>
  </tr>
  <% @accounts.each do |account| %>
	  <tr>
	    <td><%= account["id"] %></td>
	    <td><%= account["name"] %></td>
	    <td><%= account["nature"] %></td>
	    <td><%= account["balance"] %></td>
	    <td><%= account["currency_code"] %></td>
	    <td><%= link_to 'Transactions', transactions_path(account_id: account["id"]), method: :get %></td>
	  </tr>
  <% end %>
</table>
<%= button_to 'Logout', destroy_user_session_path, method: :delete %>

app/views/customers/index.html.erb
<table id="customers">
  <tr>
    <th>Customer ID</th>
    <th>Customer Identifier</th>
    <th>Delete</th>
  </tr>
  <% @customers.each do |customer| %>
	  <tr>
	    <td><a href=<%= logins_path(customer_id: customer["id"]) %>><%= customer["id"] %></td>
	    <td><%= customer["identifier"] %></td>
	    <td>
	    	<%= link_to 'Delete', customers_destroy_path(customer_id: customer["id"]), method: :delete %>
	    </td>
	  </tr>
  <% end %>
</table>

<%= button_to 'Logout', destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpectreApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/index.html.erb
<table id="customers">
  <tr>
    <th>Login ID</th>
    <th>Provider Name</th>
    <th>Customer ID</th>
    <th>Status</th>
    <th>Accounts</th>
    <th>Refresh</th>
    <th>Reconnect</th>
    <th>Delete</th>
  </tr>
  <% @logins.each do |login| %>
	  <tr>
	    <td><%= login["id"] %></td>
	    <td><%= login["provider_name"] %></td>
	    <td><%= login["customer_id"] %></td>
	    <td><%= login["status"] %></td>
	    <td><%= link_to 'Accounts', accounts_path(login_id: login["id"]), method: :get %></td>
	    <td>
	    	<%= link_to 'Refresh', logins_refresh_path(login_id: login["id"], customer_id: params[:customer_id]), method: :put %>
	    </td>
	    <td>
	    	<%= link_to 'Reconnect', logins_reconnect_path(login_id: login["id"], customer_id: params[:customer_id]), method: :put%>
	    </td>
	    <td>
	    	<%= link_to 'Delete', logins_destroy_path(login_id: login["id"], customer_id: params[:customer_id]), method: :delete %>
	    </td>
	  </tr>
  <% end %>
</table>
<%= button_to 'Create New Login', logins_create_path(customer_id: params[:customer_id]), method: :post %>
<%= button_to 'Logout', destroy_user_session_path, method: :delete %>

app/views/transactions/index.html.erb
<table id="customers">
  <tr>
    <th>Made On</th>
    <th>Description</th>
    <th>ID</th>
    <th>Account ID</th>
    <th>Amount</th>
    <th>Currency Code</th>
  </tr>
  <% @transactions.each do |transaction| %>
	  <tr>
	    <td><%= transaction["made_on"]%></td>
	    <td><%= transaction["description"]%></td>
	    <td><%= transaction["id"]%></td>
	    <td><%= transaction["account_id"]%></td>
	    <td><%= transaction["amount"]%></td>
	    <td><%= transaction["currency_code"]%></td>
	  </tr>
  <% end %>
</table>
<%= button_to 'Logout', destroy_user_session_path, method: :delete %>